[theme]
primaryColor = "#4a148c"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a237e"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 10
